
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Acer
 */
public class bill_manager extends javax.swing.JFrame {

    /**
     * Creates new form bill_manager
     */
    public void ProductTable() {
        try {
            String driverclass = "com.mysql.jdbc.Driver";
            Class.forName(driverclass);
            String url = "jdbc:mysql://localhost:3306/dairyfarm";
            String user = "root";
            String pass = "";
            Connection con = DriverManager.getConnection(url, user, pass);

            String sql = "select * from productadd";
            PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            String pid, pname, quan, price, tc;

            DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
            tb.getDataVector().removeAllElements();

            while (rs.next()) {
                pid = String.valueOf(rs.getInt("PID"));
                pname = rs.getString("PName");

                quan = String.valueOf(rs.getDouble("Quantity"));
                price = rs.getString("SellingPrice");
                tc = rs.getString("TotalCost");

                String td[] = {pid, pname, quan, price, tc};
                tb.addRow(td);
            }
        } catch (Exception ex) {
            Logger.getLogger(bill_manager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Bill() {
        try {
            String driverclass = "com.mysql.jdbc.Driver";
            Class.forName(driverclass);
            String url = "jdbc:mysql://localhost:3306/dairyfarm";
            String user = "root";
            String pass = "";
            Connection con = DriverManager.getConnection(url, user, pass);

            String sql = "select * from billhistory";
            PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            String quan, pid, pname, dt, cn, cm;
            int tprice;
            DefaultTableModel tb = (DefaultTableModel) jTable2.getModel();
            //tb.getDataVector().removeAllElements();

            while (rs.next()) {
                pid = rs.getString("PID");
                pname = rs.getString("PName");

                quan = rs.getString("Quantity");
                tprice = rs.getInt("TotalPrice");
                dt = rs.getString("Date");
                cn = rs.getString("CustomerName");
                cm = rs.getString("CustomerMobile");

                String result2 = Integer.toString(tprice);

                String td[] = {pid, pname, quan, result2, dt, cn, cm};
                tb.addRow(td);
            }

            sql = "select sum(TotalPrice) from billhistory";
            ps = con.prepareStatement(sql);

            rs = ps.executeQuery();

            if (rs.next()) {
                String y = rs.getString("sum(TotalPrice)");
                jLabel12.setText(y);
            }

        } catch (Exception ex) {
            Logger.getLogger(bill_manager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Combo() {
        try {

            String driverclass = "com.mysql.jdbc.Driver";
            Class.forName(driverclass);
            String url = "jdbc:mysql://localhost:3306/dairyfarm";
            String user = "root";
            String pass = "";
            Connection con = DriverManager.getConnection(url, user, pass);

            String sql = "select * from productadd";
            PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);

            ResultSet rs = ps.executeQuery();

            String p;

            while (rs.next()) {

                p = rs.getString("PName");

                jComboBox1.addItem(p);
            }
        } catch (Exception ex) {
            Logger.getLogger(update_product.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public bill_manager() {
        initComponents();
        ProductTable();
        Bill();
        Combo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1020));
        getContentPane().setLayout(null);

        back.setBackground(new java.awt.Color(208, 252, 197));
        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(0, 0, 77, 31);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Billings");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(836, 13, 170, 58);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Product Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(610, 140, 143, 41);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Quantity(Kg)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(610, 210, 132, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(610, 280, 47, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Customer Mobile");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(610, 350, 169, 40);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setPreferredSize(new java.awt.Dimension(10, 40));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(790, 210, 431, 40);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(790, 350, 431, 40);

        jButton2.setBackground(new java.awt.Color(208, 252, 197));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton2.setText("Add To Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1334, 166, 160, 50);

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity(kg)", "Price(tk)/kg"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(514, 741, 793, 179);

        jTable2.setBackground(new java.awt.Color(255, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "PName", "PQuantity(kg)", "Total Sell(tk)", "Date", "Customer Name", "Customer Mobile"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(235, 495, 1404, 189);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel6.setText("Product List");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(881, 703, 109, 26);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel7.setText("Bill History");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(884, 452, 98, 26);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel8.setText("Total Sell Price(tk)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1400, 760, 172, 40);

        reset.setBackground(new java.awt.Color(208, 252, 197));
        reset.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(1340, 240, 150, 50);

        jButton1.setBackground(new java.awt.Color(208, 252, 197));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1770, 894, 116, 60);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(790, 280, 431, 40);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(790, 140, 430, 40);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1500, 350, 170, 40);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel10.setText("Pay Bill (taka)");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1340, 350, 150, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(19, 57, 172));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1590, 760, 250, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\New folder\\biil manager.png")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1930, 1040);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:

        new manager_login().setVisible(true);
        new bill_manager().setVisible(false);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try {
            String driverclass = "com.mysql.jdbc.Driver";
            Class.forName(driverclass);
            String url = "jdbc:mysql://localhost:3306/dairyfarm";
            String user = "root";
            String pass = "";
            Connection con = DriverManager.getConnection(url, user, pass);

            String sql = "select * from productadd where PName=?";

            String n = jComboBox1.getSelectedItem().toString();
            String q = jTextField2.getText();
            String date = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();

            String cm = jTextField4.getText();

            if (q.isEmpty() || date.isEmpty() || cm.isEmpty() || !date.matches("^\\d{4}-(0[1-9]|1[0-2])-([12][0-9]|0[1-9]|3[01])$")) {
                JOptionPane.showMessageDialog(null, "Please fill out every field according to the requirements");
            } else {

                if (q.matches("\\d+") || q.matches("\\d+(\\.\\d+)?")) {
                    double a = Double.parseDouble(q);
                    PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);
                    ps.setString(1, n);
                    ResultSet rs = ps.executeQuery();
                    sql = "select CName from customer where CMobile=?";
                    ps = con.prepareStatement(sql);
                    ps.setString(1, cm);
                    ResultSet rs2 = ps.executeQuery();
                    String pid, pname, price, tc, quan = null;

                    DefaultTableModel tb = (DefaultTableModel) jTable2.getModel();

                    if (rs2.next()) {

                        String cn = rs2.getString("CName");
                        boolean isValidProduct = false;
                        while (rs.next()) {
                            pid = String.valueOf(rs.getInt("PID"));
                            pname = rs.getString("PName");
                            quan = String.valueOf(rs.getDouble("Quantity"));

                            double lq;
                            lq = Double.parseDouble(quan);

                            price = rs.getString("SellingPrice");
                            tc = rs.getString("TotalCost");
                            if (a <= lq) {
                                isValidProduct = true;
                                double p = Double.parseDouble(price);
                                double pp = p * a;
                                int tp1 = (int) pp;
                                String tp = String.valueOf(tp1);

                                String td[] = {pid, pname, q, tp, date, cn, cm};
                                tb.addRow(td);
                                jLabel11.setText(tp);

                                // Get the index of the newly added row
                                int rowIndex = tb.getRowCount() - 1;

// Highlight the newly added row
                                jTable2.setRowSelectionInterval(rowIndex, rowIndex);

                                sql = "insert into billhistory (PID,PName,Quantity,TotalPrice,Date,CustomerName,CustomerMobile)values(?,?,?,?,?,?,?)";
                                ps = con.prepareStatement(sql);
                                double abc = Double.parseDouble(tp);
                                ps.setString(1, pid);
                                ps.setString(2, pname);
//adsadds
                                ps.setString(3, q);
                                ps.setDouble(4, abc);
                                ps.setString(5, date);
                                ps.setString(6, cn);
                                ps.setString(7, cm);

                                ps.executeUpdate();

                                sql = "update productadd set Quantity=? where PName=?";
                                ps = con.prepareStatement(sql);

                                double qq;
                                qq = Double.parseDouble(quan);
                                qq = qq - a;

                                String formattedNumber = String.format("%.2f", qq);

                                // Store the formatted number in a variable
                                String result = formattedNumber;

                                ps.setString(1, result);
                                ps.setString(2, n);
                                ps.executeUpdate();
                                ProductTable();

                            }
                        }
                        if (!isValidProduct) {
                            JOptionPane.showMessageDialog(this, "There aren't enough units of the product available.", "Error", JOptionPane.ERROR_MESSAGE);
                        }

                        sql = "select sum(TotalPrice) from billhistory";
                        ps = con.prepareStatement(sql);

                        rs = ps.executeQuery();

                        if (rs.next()) {
                            String y = rs.getString("sum(TotalPrice)");

                            jLabel12.setText(y);
                        }

                    } else {

                        JOptionPane.showMessageDialog(null, "This phone number doesn't currently have any customers. First,kindly register");
                        new add_customer().setVisible(true);
                        new bill_manager().setVisible(false);
                        dispose();
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Please enter a valid quantity number.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }

        } catch (Exception ex) {
            Logger.getLogger(bill_manager.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:

        jTextField2.setText("");
        jDateChooser1.setDate(null);
        jTextField4.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new welcome().setVisible(true);
        new bill_manager().setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill_manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
