/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class manager_login extends javax.swing.JFrame {

    /**
     * Creates new form manager_login
     */
    public manager_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        billings = new javax.swing.JButton();
        customerdetail = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        productmanage = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1020));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Manager Directory");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(729, 0, 400, 70);

        billings.setBackground(new java.awt.Color(208, 252, 197));
        billings.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        billings.setText("Billings");
        billings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingsActionPerformed(evt);
            }
        });
        getContentPane().add(billings);
        billings.setBounds(820, 153, 224, 55);

        customerdetail.setBackground(new java.awt.Color(208, 252, 197));
        customerdetail.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        customerdetail.setText("Customer Details");
        customerdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerdetailActionPerformed(evt);
            }
        });
        getContentPane().add(customerdetail);
        customerdetail.setBounds(820, 336, 224, 55);

        jButton3.setBackground(new java.awt.Color(208, 252, 197));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1770, 910, 111, 51);

        productmanage.setBackground(new java.awt.Color(208, 252, 197));
        productmanage.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        productmanage.setText("Product Manage");
        productmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productmanageActionPerformed(evt);
            }
        });
        getContentPane().add(productmanage);
        productmanage.setBounds(820, 243, 224, 55);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\New folder\\manager.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1900, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productmanageActionPerformed
        // TODO add your handling code here:
        new product_manage().setVisible(true);
        new manager_login().setVisible(false);
        dispose();
    }//GEN-LAST:event_productmanageActionPerformed

    private void billingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingsActionPerformed
        // TODO add your handling code here:
        new bill_manager().setVisible(true);
        new manager_login().setVisible(false);
        dispose();
    }//GEN-LAST:event_billingsActionPerformed

    private void customerdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerdetailActionPerformed
        // TODO add your handling code here:
        new customer_detail().setVisible(true);
        new manager_login().setVisible(false);
        dispose();
    }//GEN-LAST:event_customerdetailActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new welcome().setVisible(true);
        new manager_login().setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manager_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billings;
    private javax.swing.JButton customerdetail;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton productmanage;
    // End of variables declaration//GEN-END:variables
}
