
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Acer
 */
public class profit_admin extends javax.swing.JFrame {

    /**
     * Creates new form profit_admin
     */
    public void Profit() {
        try {
            String driverclass = "com.mysql.jdbc.Driver";
            Class.forName(driverclass);
            String url = "jdbc:mysql://localhost:3306/dairyfarm";
            String user = "root";
            String pass = "";
            Connection con = DriverManager.getConnection(url, user, pass);

            String sql = "select*from productadd";
            PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);

            ResultSet r, rs = ps.executeQuery();

            String pn, sq, x;
            int bpr, spr;
            double pq, ts, tl, ep, cp;

            String a, b, c, d, e;

            DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();

            while (rs.next()) {
                pn = rs.getString("PName");
                pq = rs.getDouble("Quantity");
                bpr = rs.getInt("Price");

                spr = rs.getInt("SellingPrice");

                ts = 0;
                tl = pq;

                ProductBill.addItem(pn);
                sq = "select sum(Quantity) from billhistory where PName=?";

                ps = con.prepareStatement(sq);
                ps.setString(1, pn);

                r = ps.executeQuery();
                if (r.next()) {
                    x = r.getString("sum(Quantity)");
                    if (x != null) {
                        ts = Double.parseDouble(x);
                    }
                }

                pq = tl + ts;

                ep = (spr - bpr) * pq;
                cp = (spr - bpr) * ts;

                int intValue1 = (int) Math.floor(ep);
                int intValue2 = (int) Math.floor(cp);

//                a = String.valueOf(pq);
//                b = String.valueOf(ts);
//                c = String.valueOf(tl);
                d = String.valueOf(intValue1);
                e = String.valueOf(intValue2);
                
                String formattedNumber = String.format("%.2f", pq);
        
       
        
        // Store the formatted number in a variable
        String result1 = formattedNumber;
        String formattedNumber2 = String.format("%.2f", tl);
        
       
        
        // Store the formatted number in a variable
        String result2 = formattedNumber2;
        
                String formattedNumber3 = String.format("%.2f", ts);
        
       
        
        // Store the formatted number in a variable
        String result3 = formattedNumber3;

                String dt[] = {pn,result1,result3,result2,d, e};

                tb.addRow(dt);
            }
        } catch (Exception ex) {
            Logger.getLogger(profit_admin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void Bill() {
        try {
            String driverclass = "com.mysql.jdbc.Driver";
            Class.forName(driverclass);
            String url = "jdbc:mysql://localhost:3306/dairyfarm";
            String user = "root";
            String pass = "";
            Connection con = DriverManager.getConnection(url, user, pass);

            String sql = "select * from billhistory";
            PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);

            ResultSet rs = ps.executeQuery();
            DefaultTableModel tb = (DefaultTableModel) jTable2.getModel();

            String pn, pq, tp, dt;
            while (rs.next()) {
                pn = rs.getString("PName");

                pq = rs.getString("Quantity");
                tp = rs.getString("TotalPrice");
                dt = rs.getString("Date");

                String td[] = {pn, pq, tp, dt};
                tb.addRow(td);
            }

        } catch (Exception ex) {
            Logger.getLogger(profit_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public profit_admin() {
        initComponents();
        Bill();
        Profit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ProductBill = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1020));
        getContentPane().setLayout(null);

        back.setBackground(new java.awt.Color(208, 252, 197));
        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(0, 0, 77, 31);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Profit & Bills");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(812, 0, 280, 80);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(225, 255, 86));
        jLabel2.setText("Profit");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(904, 121, 80, 29);

        jTable1.setBackground(new java.awt.Color(255, 255, 216));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PName", "Total Quantity(kg)", "Total Sold(kg)", "Total Left(kg)", "Expected Profit(TK)", "Profit Till now(TK)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(288, 153, 1373, 242);

        jTable2.setBackground(new java.awt.Color(255, 255, 216));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity(kg)", "Total Price(TK)", "Date"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(288, 482, 1373, 181);

        jTable3.setBackground(new java.awt.Color(255, 255, 216));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date ", "Quantity(kg)", "Total Price(TK)"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(875, 755, 786, 180);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(225, 255, 86));
        jLabel3.setText("Bill History");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(883, 439, 130, 29);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(225, 255, 86));
        jLabel4.setText("Product Bill History");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(875, 712, 220, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Select Item");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(288, 766, 117, 25);

        ProductBill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProductBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductBillActionPerformed(evt);
            }
        });
        getContentPane().add(ProductBill);
        ProductBill.setBounds(457, 755, 239, 36);

        jButton1.setBackground(new java.awt.Color(208, 252, 197));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(513, 809, 93, 33);

        jButton2.setBackground(new java.awt.Color(208, 252, 197));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1740, 910, 135, 52);

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\New folder\\bil2.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1920, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new admin().setVisible(true);
        new profit_admin().setVisible(false);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void ProductBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductBillActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ProductBillActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String driverclass = "com.mysql.jdbc.Driver";
            Class.forName(driverclass);
            String url = "jdbc:mysql://localhost:3306/dairyfarm";
            String user = "root";
            String pass = "";
            Connection con = DriverManager.getConnection(url, user, pass);

            String name = ProductBill.getSelectedItem().toString();
            String sql = "select Quantity,TotalPrice,Date from billhistory where PName=?";
            PreparedStatement ps = (PreparedStatement) con.prepareStatement(sql);

            ps.setString(1, name);

            ResultSet rs = ps.executeQuery();

            String date, q, tp;

            DefaultTableModel tb = (DefaultTableModel) jTable3.getModel();
            tb.setRowCount(0);
            boolean found = false;
            while (rs.next()) {
                q = String.valueOf(rs.getDouble("Quantity"));
                tp = String.valueOf(rs.getInt("TotalPrice"));
                date = rs.getString("Date");

                String dt[] = {date, q, tp};
                tb.addRow(dt);
                found = true;
            }
            if (!found) {
                JOptionPane.showMessageDialog(null, "The item hasn't been sold yet");
            }

        } catch (Exception ex) {
            Logger.getLogger(profit_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new welcome().setVisible(true);
        new profit_admin().setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profit_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profit_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profit_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profit_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profit_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ProductBill;
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
